name: wine_quality_mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy>=1.26.0
    - pandas>=2.1.0
    - scikit-learn>=1.3.0
    - mlflow>=2.19.0
    - matplotlib>=3.8.0
    - seaborn>=0.13.0
    - joblib>=1.3.2

