name: wine_quality_mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - numpy==1.24.3
    - pandas==2.0.3
    - scikit-learn==1.3.0
    - mlflow==2.19.0
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - joblib==1.3.2

